DROP TABLE IF EXISTS TRANSACTION_DETAILS;

CREATE TABLE TRANSACTION_DETAILS
   (TRANSACTION_ID BIGINT PRIMARY KEY,
	AMOUNT DOUBLE NOT NULL,
	TYPE VARCHAR(100) NOT NULL,
	PARENT_ID BIGINT DEFAULT NULL,
	CONSTRAINT FK_Parent
    FOREIGN KEY (PARENT_ID)
    REFERENCES TRANSACTION_DETAILS(TRANSACTION_ID)
);




